### ISSUE TITLE
選單不會變成中文

### ISSUE THREAD

**Issue by asika32764** [smstw/joomla-coding-standards#17]
選單已經翻譯了
https://github.com/smstw/joomla-coding-standards/blob/gh-pages/manual/zh-TW/menu.md

但頁面上不會變成中文
@bblurock 看看怎麼回事吧

**Comment by asika32764** [comment]
http://smstw.github.io/joomla-coding-standards/

**Comment by asika32764** [comment]
等選單問題解決我就要發 PR 回官方了

**Comment by bblurock** [comment]
在`manual.js`點選選單的時候，我忘了加上 `populateMenu();`

**Comment by asika32764** [comment]
Close by #20
