### ISSUE TITLE
Analysis 與 menu 翻譯

### ISSUE THREAD

**Issue by asika32764** [smstw/joomla-coding-standards#5]
https://github.com/smstw/joomla-coding-standards/blob/gh-pages/manual/zh-TW/appendices/analysis.md

https://github.com/smstw/joomla-coding-standards/blob/gh-pages/manual/zh-TW/menu.md

**Comment by michael520** [comment]
有看到了 lol

**Comment by bblurock** [comment]
之前翻的， @michael520  參考一下。才不會白做ＸＤ
- [簡介](coding-standards/introduction.md)
- [源碼管理](coding-standards/chapters/source-code-management.md)
- **編碼標準**
  - [基礎指引](coding-standards/chapters/basic-guidelines.md)
  - [行內註解](coding-standards/chapters/inline-comments.md)
  - [區塊註解(DocBlocks)](coding-standards/chapters/docblocks.md)
  - [PHP編碼標準](coding-standards/chapters/php.md)
  - [XML](coding-standards/chapters/xml.md)
- **使用者端語法風格指引**
  - [HTML](coding-standards/chapters/html.md)
  - [CSS](coding-standards/chapters/css.md)
  - [JavaScript](coding-standards/chapters/javascript.md)
- **附錄**
  - [程式碼分析工具](appendices/analysis.md)
  - [範例](appendices/examples.md)

**Comment by michael520** [comment]
喔！~~謝謝謝謝 :+1:
