### ISSUE TITLE
[Discuss] 另開一個 repository 放 codesniffer 如何?

### ISSUE THREAD

**Issue by LeoOnTheEarth** [smstw/joomla-coding-standards#9]
目前是打算把 codesniffer 的部分移到另一個 repository
並且註冊到 packagist 讓他可以用 composer 安裝

日後 codesniffer 的部分會整合在 https://github.com/smstw/sms-dev 裡面

**Comment by asika32764** [comment]
這個 repo 是 clone 官方來翻譯用的，code sniffer 我們在自己的 organization 看要怎麼管理都 OK

**Comment by LeoOnTheEarth** [comment]
開好囉 https://github.com/smstw/sms-php-code-sniffer

**Comment by LeoOnTheEarth** [comment]
Packagist 頁面 https://packagist.org/packages/smstw/php-code-sniffer

**Comment by asika32764** [comment]
如果你之後想避免用到 packagist 的公開資源或是未來專案有私密資訊的話，可以參考這個寫法
https://github.com/smstw/sms-uni-dev/issues/2#issuecomment-55493491

**Comment by LeoOnTheEarth** [comment]
先 closed 囉~

**Comment by LeoOnTheEarth** [comment]
> smstw/sms-uni-dev#2 (comment)

測試了一下
如果用 package 的方式安裝
若 master branch 有更新的話
使用 composer update 不會抓最新的 zip 檔下來
必需要更改 package 裡的 version 之後，composer update 才會正常更新

**Comment by asika32764** [comment]
是的，就是從 composer.json 裡面改即可，他的功能就是模擬一個假的 package 在 composer.json 裡面
